/* ==========================================================================
   The 200 passwords this site refuses.

   Source: the 200 most frequent entries of the SecLists "10k-most-common"
   password list (danielmiessler/SecLists, MIT licence), taken on 2026-09-09,
   with sexual and abusive terms removed so this file can sit in a public
   federal-sprint repository.

   Why a list at all: a ten-character minimum stops "abc123" but not
   "1234567890", "qwertyuiop" or "password123", and those are among the most
   guessed strings on the internet. Most of the list is shorter than ten
   characters, which is why _password.js does not compare the raw string: it
   lower-cases, undoes the usual leet substitutions and strips the padding
   people add to reach a length rule, then compares every form against this
   list. So "P@ssword1!" is refused by the entry "password".

   Generated by scratchpad/gen-lists.mjs.
   ========================================================================== */
export const COMMON_PASSWORDS = [
 'password','123456','12345678','1234','qwerty','12345','dragon','baseball','football','letmein','monkey','abc123',
 'mustang','michael','shadow','master','jennifer','111111','2000','jordan','superman','harley','1234567','hunter',
 'trustno1','ranger','buster','thomas','tigger','robert','soccer','batman','test','pass','killer','hockey','george',
 'charlie','andrew','michelle','love','sunshine','jessica','pepper','daniel','access','123456789','654321','joshua',
 'maggie','starwars','silver','william','dallas','yankees','123123','ashley','666666','hello','amanda','orange',
 'biteme','freedom','computer','thunder','nicole','ginger','heather','hammer','summer','corvette','taylor','austin',
 '1111','merlin','matthew','121212','golfer','cheese','princess','martin','chelsea','patrick','richard','diamond',
 'yellow','bigdog','secret','asdfgh','sparky','cowboy','camaro','anthony','matrix','falcon','iloveyou','bailey',
 'guitar','jackson','purple','scooter','phoenix','aaaaaa','morgan','tigers','porsche','mickey','maverick','cookie',
 'nascar','peanut','justin','131313','money','samantha','panties','steelers','joseph','snoopy','boomer','whatever',
 'iceman','smokey','gateway','dakota','cowboys','eagles','chicken','black','zxcvbn','please','andrea','ferrari',
 'knight','melissa','compaq','coffee','johnny','bulldog','welcome','james','player','ncc1701','wizard','scooby',
 'charles','junior','internet','mike','brandy','tennis','banana','monster','spider','lakers','miller','rabbit',
 'enter','mercedes','brandon','steven','fender','john','yamaha','diablo','chris','boston','tiger','marine',
 'chicago','rangers','gandalf','winter','barney','edward','raiders','badboy','spanky','bigdaddy','johnson',
 'chester','london','midnight','blue','fishing','000000','hannah','slayer','11111111','rachel','redsox','thx1138',
 'asdf','marlboro','panther','zxcvbnm','arsenal','oliver','qazwsx','mother',
];
