/* ==========================================================================
   THE PRICE TABLE — loader and combination guards

   This adapts the verified 56-row table into the app's PriceItem shape and,
   more importantly, enforces the table's own combination rules.

   🔴 WHY THE GUARDS MATTER MORE THAN THE PRICES.
   Two figures can both be true and still be wrong when added. A MEPS visit
   total already contains the labs; a CMS allowed amount does not. A whole-year
   excess figure already contains every visit in the ledger. Adding across those
   is the single most common way a cost-of-illness total becomes meaningless,
   and it is exactly what Dr. Phillips probes for.

   The table ships machine-readable flags for this — summable,
   mutually_exclusive_with, bundles_ancillaries — because, in the table's own
   words, "a rule written only in prose is not a guard, it is a wish."
   This module is where those flags actually bite.

   AUDIT: every row reproduces from the federal file it cites — most as Total RVU
   x $33.4009 (the CY2026 non-QP conversion factor), the labs as a direct CLFS rate
   lookup, two from OPPS Addendum B, one as hospital APC $426.30 + physician $118.24
   = $544.54, and the rest re-read in the cited report or table. The live counts are
   TABLE_AUDIT_LINE below, generated by the audit rather than typed here.
   Run it: python3 data/verify_price_table.py  (exit 1 on any FAIL).
   ========================================================================== */

import raw from '@/data/prices.json';
import extraSynonyms from '@/data/synonyms.json';
import type { PriceItem, PriceBasis, Attribution, Confidence } from './types';

interface RawItem {
  id: string;
  label: string;
  plain_language_synonyms?: string[];
  value_usd: number | null;
  out_of_pocket_usd?: number | null;
  basis: string;
  attribution?: string;
  summable?: boolean;
  mutually_exclusive_with?: string[];
  bundles_ancillaries?: boolean;
  year: string;
  geography?: string;
  population?: string;
  coverage_statement?: string;
  source_title?: string;
  source_url?: string;
  agency?: string;
  agency_display?: string;
  confidence?: string;
  code?: string;
  loinc?: string;
  loinc_long_common_name?: string;
  loinc_source?: string;
  pfs_status_indicator?: string;
  alternates?: Record<string, unknown>;
}

const RAW_ITEMS = (raw as { items: RawItem[] }).items;

/* ==========================================================================
   THE WORDS PEOPLE ACTUALLY USE — data/synonyms.json

   A person types "urgent care", "stomach camera", "PT", "the ER". Those are not
   the labels a fee schedule uses, and a phrase that lands nowhere reads to the
   person as "this tool has no figure for what happened to me".

   So the extra plain-language phrases live in their own file and are merged
   here, in ONE place, for the browser and the Cloudflare functions alike.
   data/prices.json is never edited to add a way of saying something: this file
   adds no price, no row and no source — only another door into a row that
   already exists with its own federal file behind it.
   ========================================================================== */

const EXTRA_SYNONYMS: Record<string, string[]> =
  (extraSynonyms as { synonyms: Record<string, string[]> }).synonyms ?? {};

/** Why a lay phrase lands on the row it lands on, where a reader would ask. */
export const SYNONYM_NOTES: Record<string, string> =
  (extraSynonyms as { notes?: Record<string, string> }).notes ?? {};

/** Ids in data/synonyms.json that name no row. Must always be empty — the test
 *  suite fails the build on one, because a synonym for a row that does not
 *  exist is a phrase that silently matches nothing. */
export function unknownSynonymIds(): string[] {
  const real = new Set(RAW_ITEMS.map((r) => r.id));
  return Object.keys(EXTRA_SYNONYMS).filter((id) => !real.has(id));
}

/** Merge, keeping the table's own wording first and dropping repeats. */
function synonymsFor(r: RawItem): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const s of [...(r.plain_language_synonyms ?? []), ...(EXTRA_SYNONYMS[r.id] ?? [])]) {
    const k = s.trim().toLowerCase();
    if (!k || seen.has(k)) continue;
    seen.add(k); out.push(s.trim());
  }
  return out;
}

/** Fields the base PriceItem type does not carry, kept alongside by id. */
export interface Rules {
  summable: boolean;
  mutuallyExclusiveWith: string[];
  bundlesAncillaries: boolean;
  alternates?: Record<string, unknown>;
}

const RULES = new Map<string, Rules>();

function normBasis(b: string): PriceBasis {
  switch (b) {
    case 'allowed_amount': return 'allowed';
    case 'out_of_pocket': return 'out_of_pocket';
    case 'total_expenditure': return 'total_expenditure';
    case 'payment': return 'payment';
    case 'charge': return 'charge';
    case 'wage': return 'wage';
    default: return 'payment';
  }
}

export const TABLE: PriceItem[] = RAW_ITEMS.map((r) => {
  RULES.set(r.id, {
    summable: r.summable !== false,
    mutuallyExclusiveWith: r.mutually_exclusive_with ?? [],
    bundlesAncillaries: !!r.bundles_ancillaries,
    alternates: r.alternates,
  });
  return {
    id: r.id,
    label: r.label,
    synonyms: synonymsFor(r),
    valueUsd: r.value_usd,
    outOfPocketUsd: r.out_of_pocket_usd ?? null,
    basis: normBasis(r.basis),
    attribution: (r.attribution === 'excess' ? 'excess' : 'gross') as Attribution,
    year: r.year,
    geography: r.geography ?? 'not stated',
    population: r.population ?? 'not stated',
    coverage: r.coverage_statement ?? '',
    sourceTitle: r.source_title ?? 'not stated',
    sourceUrl: r.source_url ?? '',
    agency: r.agency ?? undefined,
    agencyDisplay: r.agency_display ?? undefined,
    confidence: (r.confidence as Confidence) ?? 'REPORTED',
    code: r.code,
    loinc: r.loinc || undefined,
    loincName: r.loinc_long_common_name || undefined,
    loincSource: r.loinc_source || undefined,
    pfsStatus: r.pfs_status_indicator || undefined,
  };
});

/** Only these may enter an itemized total. Everything else sits beside it. */
export const SUMMABLE = TABLE.filter((i) => RULES.get(i.id)?.summable !== false);

/** Items a person can add to a journey — priced and summable. */
export const SELECTABLE = SUMMABLE.filter((i) => i.valueUsd !== null);

export function rulesFor(id: string): Rules {
  return RULES.get(id) ?? { summable: true, mutuallyExclusiveWith: [], bundlesAncillaries: false };
}

export interface ConflictReport {
  /** ids that must be dropped from the total, with the reason shown to the user */
  conflicts: { keep: string; drop: string; reason: string }[];
  /** ids present that are not summable at all */
  nonSummable: string[];
  /** true if any line already bundles the labs/imaging someone may also have added */
  bundlingRisk: boolean;
}

/**
 * 🔴 THE GUARD. Given the ids in a ledger, report what must not be summed.
 * Called before any total is displayed. A conflict is surfaced to the user in
 * plain words, never silently resolved — the person should see why two true
 * numbers cannot be added.
 */
export function checkCombination(ids: string[]): ConflictReport {
  const present = new Set(ids);
  const conflicts: ConflictReport['conflicts'] = [];
  const nonSummable: string[] = [];
  let bundlingRisk = false;

  for (const id of ids) {
    const r = rulesFor(id);
    if (!r.summable) nonSummable.push(id);
    if (r.bundlesAncillaries) bundlingRisk = true;

    for (const ex of r.mutuallyExclusiveWith) {
      if (ex === '__ALL_PER_EVENT_LINES__') {
        // a whole-year figure that already contains every visit in the ledger
        for (const other of ids) {
          if (other === id) continue;
          conflicts.push({
            keep: id, drop: other,
            reason: 'This is a whole-year total that already contains every visit, test and scan. '
                  + 'Adding individual events on top of it counts the same care twice.',
          });
        }
      } else if (present.has(ex)) {
        conflicts.push({
          keep: id, drop: ex,
          reason: 'These two figures measure the same care in two different ways. '
                + 'Both are true; their sum is not.',
        });
      }
    }
  }
  return { conflicts, nonSummable, bundlingRisk };
}

/** Human-readable note when MEPS-style bundled figures sit beside CMS line items. */
export function bundlingNote(ids: string[]): string | null {
  const bundled = ids.filter((id) => rulesFor(id).bundlesAncillaries);
  if (!bundled.length) return null;
  const unbundled = ids.filter((id) => !rulesFor(id).bundlesAncillaries);
  if (!unbundled.length) return null;
  return 'Some lines here already include the labs and imaging ordered during the visit, and '
       + 'others do not, because they come from sources that count differently. Where both are '
       + 'present the total may count some tests twice. Open any line to see which kind it is.';
}

export const TABLE_VERSION = (raw as { _version?: string })._version ?? 'unknown';

/** ONE line, generated by data/verify_price_table.py and written back onto the
 *  table on a clean run: rows, how many reproduce, the CY2024 companion figures,
 *  the locality figures and the date. The version string is a result, not a label. */
export const TABLE_AUDIT_LINE = (raw as { _audit?: string })._audit ?? '';
export const PROHIBITED = (raw as { _prohibited_derivations?: unknown })._prohibited_derivations;
