#!/bin/bash
# ==========================================================================
# export-public-repo.sh — make the thing /adopt describes actually obtainable.
#
# R3, scale, verbatim: "/adopt tells an agency to edit data/conditions.json and
# run python3 data/verify_price_table.py, and there is no repository on earth
# where those files can be obtained. The adoption door is beautifully described
# and locked."
#
# This unlocks it without needing anyone's permission or any account: a clean,
# self-contained copy of the application, with a README a stranger can run from,
# written to runs/TOPX-HHS-PHASE2/waypoint-public/ and packed into
# public/waypoint-ledger-source.tar.gz so the site itself serves the source.
#
# 🔴 IT PUBLISHES NOTHING. No git remote, no push, no deploy. Whether and where
#    to put this on GitHub is Bo's decision, and it is one command away when he
#    makes it.
#
# What is deliberately left out: node_modules, build output, screenshots, the
# internal work orders, and every secret. The script REFUSES to finish if it
# finds a credential in what it just copied.
#
#   bash scripts/export-public-repo.sh              # export + tarball
#   DEST=/tmp/wl bash scripts/export-public-repo.sh # somewhere else
#   VERIFY=1 bash scripts/export-public-repo.sh     # also npm ci && npm test in the copy
# ==========================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${DEST:-$(cd "$ROOT/.." && pwd)/waypoint-public}"
TARBALL="$ROOT/public/waypoint-ledger-source.tar.gz"

say() { printf '%s\n' "$*"; }

say "export-public-repo"
say "  from  $ROOT"
say "  to    $DEST"

rm -rf "$DEST"
mkdir -p "$DEST"

# Everything that is not source, not ours to give, or regenerated by a build.
rsync -a \
  --exclude '.git' \
  --exclude 'node_modules' \
  --exclude '.next' \
  --exclude 'shots' \
  --exclude 'shots2' \
  --exclude 'WORK-ORDERS' \
  --exclude '.wrangler' \
  --exclude 'cf/.dev.vars' \
  --exclude 'cf/.dev.vars.*' \
  --exclude 'cf/out' \
  --exclude 'cf/out-*' \
  --exclude 'cf/.stage-*' \
  --exclude 'cf/node_modules' \
  --exclude 'tsconfig.tsbuildinfo' \
  --exclude '*.jsonl' \
  --exclude '.DS_Store' \
  --exclude 'public/waypoint-ledger-source.tar.gz' \
  "$ROOT/" "$DEST/"

# ---------------------------------------------------------------- safety gate
# A public copy that carries a token is worse than no public copy. Look for the
# shapes a real credential takes, in the files we just wrote.
say "scanning the copy for anything that should not leave"
SECRET_RE='CLOUDFLARE_API_TOKEN[[:space:]]*=[[:space:]]*["'"'"']?[A-Za-z0-9_-]{12}'
SECRET_RE="$SECRET_RE"'|(ADMIN_TOKEN|INTERVIEW_KEY)[[:space:]]*=[[:space:]]*["'"'"'][A-Za-z0-9+/_=-]{16}'
SECRET_RE="$SECRET_RE"'|(sk|pk)-[A-Za-z0-9]{20}|BEGIN [A-Z ]*PRIVATE KEY|AKIA[0-9A-Z]{16}'
# This script carries the patterns themselves, so it is the one file exempt from
# its own scan. Everything else in the copy is scanned, including every dotfile.
HITS="$(grep -rIlE "$SECRET_RE" "$DEST" 2>/dev/null | grep -v '/scripts/export-public-repo\.sh$' || true)"
if [ -n "$HITS" ]; then
  say "🔴 REFUSING TO EXPORT — a credential-shaped string is in:"; printf '%s\n' "$HITS"
  rm -rf "$DEST"; exit 3
fi
say "  clean"

# ------------------------------------------------- a config nobody can misfire
# Our Cloudflare project name and resource ids are useless to anyone else and
# dangerous to leave pointed at us, so the copy ships placeholders and the
# README gives the three commands that produce real ones.
python3 - "$DEST/cf/wrangler.toml" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p, encoding='utf-8').read()
s = s.replace('name = "waypoint-ledger"', 'name = "YOUR-PAGES-PROJECT"        # wrangler pages project create YOUR-PAGES-PROJECT')
s = re.sub(r'^id = "[0-9a-f]{32}"$', 'id = "YOUR_KV_NAMESPACE_ID"        # wrangler kv namespace create LEDGER', s, flags=re.M)
s = re.sub(r'^database_id = "[0-9a-f-]{36}"$', 'database_id = "YOUR_D1_DATABASE_ID"   # wrangler d1 create waypoint-ledger', s, flags=re.M)
open(p, 'w', encoding='utf-8').write(s)
PY

# --------------------------------------------- a build that does not surprise
# Our static build re-exports this copy on every run, which is right for us and
# baffling for a stranger (it would write a sibling directory outside their
# checkout). The catalog generator stays; the export step comes out.
python3 - "$DEST/cf/build-static.sh" <<'STRIP'
import sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
line = '( cd "$ROOT" && bash scripts/export-public-repo.sh > /dev/null )\n'
s = s.replace(line, '# (the public export step runs only in the upstream working tree)\n')
open(p, "w", encoding="utf-8").write(s)
STRIP

# --------------------------------------------------------------------- README
cat > "$DEST/README.md" <<'MD'
# Waypoint Ledger

A person types the visits and tests they had. Each phrase maps to a standard unit of care. That unit is
priced at **one published federal figure** that carries its year, its basis and the population it describes.
Where no federal file describes the person in front of it, the tool says so and counts the absence instead of
filling it with the nearest number.

**No model, average or interpolation produces a dollar figure anywhere in this codebase.** If you keep one
thing when you adapt this, keep that.

Live: <https://waypoint-ledger.pages.dev> · How to adapt it: <https://waypoint-ledger.pages.dev/adopt> ·
The API: <https://waypoint-ledger.pages.dev/developers>

---

## Run it

```bash
npm install
npm run build:static          # writes the static export to cf/out
npm test                      # the unit suite: the matcher, the pricing rules, the exports, the catalog
```

The front end alone needs nothing else:

```bash
npm run dev                   # http://localhost:3000
```

## Run the whole stack, with the database

The write paths (corrections, care gaps, the burden survey, saved journeys, passkeys) are Cloudflare Pages
Functions over D1 and KV. Locally that is one command once you have created the two resources on your own
Cloudflare account:

```bash
npx wrangler login
npx wrangler d1 create waypoint-ledger            # put the id in cf/wrangler.toml
npx wrangler kv namespace create LEDGER           # put the id in cf/wrangler.toml
npx wrangler pages project create YOUR-PAGES-PROJECT

npm run db:migrate:local                          # applies cf/migrations/*.sql
npm run dev:full                                  # http://localhost:8788 — pages + functions + local D1
```

`cf/wrangler.toml` ships with placeholders (`YOUR_D1_DATABASE_ID`, `YOUR_KV_NAMESPACE_ID`,
`YOUR-PAGES-PROJECT`) so a first run cannot accidentally point at somebody else's project.

Two secrets are optional and only needed for the interview reader and the admin views:

```bash
npx wrangler pages secret put ADMIN_TOKEN   --project-name YOUR-PAGES-PROJECT
npx wrangler pages secret put INTERVIEW_KEY --project-name YOUR-PAGES-PROJECT   # 32 random bytes, base64
```

## Deploy

```bash
npm run db:migrate:remote
npm run build:static
cd cf && npx wrangler pages deploy out --project-name YOUR-PAGES-PROJECT
bash cf/verify-live.sh https://your-deployment-url
```

`verify-live.sh` curls the origin and exits non-zero if any promise the pages make is not true of the server.
Run it after every deploy; a deploy that is not verified is a deploy you are guessing about.

## The two commands that keep the numbers honest

```bash
python3 data/verify_price_table.py     # re-derives every published figure from the file it cites; exit 1 on drift
node    scripts/gen-locality-table.mjs # recomputes every CMS locality figure; exit 1 on one cent of drift
```

A published number that no longer reproduces from its source cannot leave this repository. That is the whole
trust model, and it is two commands long.

## Where things are

| Path | What is in it |
|---|---|
| `data/prices.json` | Every published federal figure, each with its file, year, basis, population and combination rules. |
| `data/state-prices.json` | The Medicare allowed amount for each priced code in each CMS payment locality. |
| `data/conditions.json` | The conditions the picker offers, with ICD-10-CM codes and an explicit null where no figure is published. |
| `lib/` | The matcher, the pricing rules, the fit rules, the survey definition. Imported by both the React app and the Cloudflare Functions — never a second copy. |
| `app/`, `components/` | Next.js 15 app router, static export. |
| `cf/functions/api/` | The API. One file per route. |
| `cf/migrations/` | The whole database schema, in order. Add a migration; never edit `0001_init.sql`. |
| `public/data.json` | The DCAT-US v1.1 catalog describing every open file this project publishes. |
| `tests/` | `npm test`. The suite imports the same modules the app does. |

## Adapting it

`/adopt` on the live site is the procedure, and it is short:

- **Another condition** — one object in `data/conditions.json` pointing at a row that already exists.
- **Another state** — nothing to edit. All 109 CMS payment localities ship with the tool.
- **Another population** — one branch in `lib/fit.ts`, which holds the whole "does this figure describe this
  person" rule in one function.
- **Your own community, counted separately** — append `?c=your-org-slug` to the survey link and every
  response through it carries that channel, in the public export as well as in your own reading of it.

## Licence

- **The software** — Apache License 2.0. See `LICENSE`.
- **The data** — CC0 1.0 (public domain dedication). The federal figures are U.S. Government works and are
  already public domain; our arrangement of them is dedicated to the public domain too. See `NOTICE`.

Attribution is welcome and not required. Corrections are worth more than attribution:
**bo@precisionfederal.com**.

## A note on what this is not

Nothing here is published by, endorsed by, or on behalf of any federal agency. The register's counts are what
members of the public said, published with their N and with small cells suppressed — never a claim about what
anyone owes or paid.
MD

# ------------------------------------------------------------------- tarball
say "packing $TARBALL"
mkdir -p "$ROOT/public"
tar -czf "$TARBALL" -C "$(dirname "$DEST")" "$(basename "$DEST")"

FILES="$(find "$DEST" -type f | wc -l | tr -d ' ')"
SIZE="$(du -sh "$DEST" | cut -f1 | tr -d ' ')"
TSIZE="$(du -h "$TARBALL" | cut -f1 | tr -d ' ')"
say ""
say "exported $FILES files ($SIZE) to $DEST"
say "tarball  $TSIZE at public/waypoint-ledger-source.tar.gz  (served at /waypoint-ledger-source.tar.gz)"
say "nothing was pushed anywhere."

if [ "${VERIFY:-0}" = "1" ]; then
  say ""
  say "verifying the copy stands on its own: npm ci && npm test"
  ( cd "$DEST" && npm ci --no-audit --no-fund --silent && npm test )
  say "the exported tree passes its own tests."
fi
